### ISSUE TITLE
submit to plugin registry for Redbean FVM

### ISSUE THREAD

**Issue by r3wt** [filisko/redbean-validation-plugin#1]
Hi, @Filisko I am the author of a similar plugin with a different implementation and style (declarative). It would be great if you would submit your plugin to the registry of redbean plugins (by emailing Gabor gabor@redbeanphp.com), as it offers a more traditional alternative to what my plugin offers, and i feel like the vast majority of the redbean community would benefit from the more traditional alternative your plugin provides.

Regards, 
         Garrett

**Comment by filisko** [comment]
Hi @r3wt ! I actually used RedBean FVM :smile: and yes, more or less that is why I wanted to do a plugin like mine, so, provide a more "common" way to do filtering and validations to our models.

Thank you, will email him and see what he says.

**Comment by filisko** [comment]
Gabor just added the plugin to the plugins list of the website :smile: 

http://www.redbeanphp.com/index.php?p=/plugins
